version: "3.9"

services:
  postgres:
    image: postgres:15
    container_name: service_provider_db
    environment:
      POSTGRES_DB: Service_Provider
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5434:5432"   # Use 5434 if 5432 already used by your global postgres
    volumes:
      - service_provider_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      retries: 5

  service_provider_service:
    build: .
    container_name: service_provider_service
    restart: unless-stopped
    environment:
      POSTGRES_DB: Service_Provider
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_HOST: postgres
      POSTGRES_PORT: 5432
    depends_on:
      postgres:
        condition: service_healthy
    ports:
      - "8002:8002"
    command: >
      sh -c "python manage.py migrate &&
             gunicorn service_provider_service.wsgi:application --bind 0.0.0.0:8002 --workers 3"

volumes:
  service_provider_data:
